# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "32a01e51-75ba-4da8-afcf-b76d92314f06"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # cocoapods

  # increment_build_number

  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    api_token: "dd9285bda31e8957d5a93bfd5014cc9ef0768486",
    build_secret: "146f8f1ed45c7579d8695d68f4514a6ef7f88b1bb74d148004250382ff30ed21"
  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
